sudo: required
services:
- docker
os:
- linux
env:
  global:
  - DOCKER_IMAGE_NAME="helloworld"
  - DOCKER_HUB_ORG="idkaryadi"

before_script:
- openssl aes-256-cbc -K $encrypted_c000e4d3c897_key -iv $encrypted_c000e4d3c897_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- sudo docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
- sudo chmod +x deploy.sh
- sudo chmod 600 deploy_rsa
after_script:
- sudo docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID} .
- sudo docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID}
- sudo docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID}
  ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
- sudo docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:latest
- ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
- ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR 'bash -s' < deploy.sh
